version: "3"
services:

  ##
  ## Start services required for Openblocks (MongoDB and Redis)
  ##
  mongodb:
    image: "docker-proxy.service.genixventures.com/t7tran/mongo:4.4.9"
    read_only: true
    environment:
      MONGO_INITDB_DATABASE: openblocks
      MONGO_INITDB_ROOT_USERNAME: openblocks
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - mongo:/data/db:rw
      - mongotmp:/tmp:rw

  redis:
    image: docker-proxy.service.genixventures.com/redis:7-alpine


  ##
  ## Start Openblocks backend services (api-service and node-service)
  ##
  openblocks-api-service:
    image: openblocksdev/openblocks-ce-api-service:1.1.6
    read_only: true
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    environment:
      # PUID: "9001"
      # PGID: "9001"
      MONGODB_URI: "mongodb://openblocks:secret123@mongodb/openblocks?authSource=admin"
      REDIS_URL: "redis://redis:6379"
      JS_EXECUTOR_URI: "http://openblocks-node-service:6060"
      ENABLE_USER_SIGN_UP: "true"
      ENCRYPTION_PASSWORD: "openblocks.dev"
      ENCRYPTION_SALT: "openblocks.dev"
      CORS_ALLOWED_DOMAINS: "*"
    depends_on:
      - mongodb
      - redis
    volumes:
      - tmp:/openblocks/api-service/logs
      - tmp:/tmp

  openblocks-node-service:
    image: openblocksdev/openblocks-ce-node-service:1.1.6
    read_only: true
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      # PUID: "9001"
      # PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
    depends_on:
      - openblocks-api-service
    volumes:
      - tmp:/tmp

  ##
  ## Start Openblocks web frontend
  ##
  openblocks-frontend:
    image: openblocksdev/openblocks-ce-frontend:1.1.6
    read_only: true
    ports:
      - "3000:3000"
    environment:
      # PUID: "9001"
      # PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
      OPENBLOCKS_NODE_SERVICE_URL: "http://openblocks-node-service:6060"
    depends_on:
      - openblocks-node-service
      - openblocks-api-service
      - mysql
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./noop.sh:/docker-entrypoint.d/01-update-nginx-conf.sh:ro
      - ./noop.sh:/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh:ro
      - tmp:/var/cache/nginx/client_temp
      - tmp:/var/cache/nginx/proxy_temp
      - tmp:/var/cache/nginx/fastcgi_temp
      - tmp:/var/cache/nginx/uwsgi_temp
      - tmp:/var/cache/nginx/scgi_temp
      - tmp:/var/run


  mysql:
    image: docker-proxy.service.genixventures.com/mysql:5.7
    read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysqltmp:/tmp:rw
      - mysqltmp:/var/run/mysqld:rw

volumes:
  mongo:
  mongotmp:
  mysql:
  mysqltmp:
  tmp:
